---
services:
  jellyfin:
    labels:
      lagoon.type: basic
      lagoon.service.usecomposeports: true
      lagoon.volumes.data.path: /data
      lagoon.volumes.config.path: /config
      lagoon.volumes.transcode.path: /transcode
    image: jellyfin/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Australia/Sydney
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/media/movies:/data/movies
    ports:
      - 8096:8096
    restart: unless-stopped

volumes:
    data:
      labels:
        lagoon.type: persistent
    config:
      labels:
        lagoon.type: persistent
    transcode:
      labels:
        lagoon.type: persistent

