---
services:
  jellyfin:
    labels:
      lagoon.type: basic
      lagoon.service.usecomposeports: true
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - TZ=Australia/Sydney
      - NVIDIA_VISIBLE_DEVICES=all
    volumes:
      - /mnt/media/movies:/data/movies
    ports:
      - 8096:8096
    runtime: nvidia
    restart: unless-stopped
